### ISSUE TITLE
Hanging if clause in sec 4.3

### ISSUE THREAD

**Issue by mbtaylor** [ivoa-std/DataLink#1]
Section 4.3 contains the sentence

    "If this SIA service supported querying specific data collections via
    a custom parameter named COLLECTION. The following PARAM describes the
    custom parameter, including the possible values:"

Something's missing, but I don't know what.

**Comment by Bonnarel** [comment]
The period coming after COLLECTION had to be suppressed and replaced by a comma.

**Comment by Bonnarel** [comment]
Done with PR #4 which is merged. Requires an erratum on 1.0
