### ISSUE TITLE
replacing "resource" by "endpoint" when appropriate

### ISSUE THREAD

**Issue by Bonnarel** [ivoa-std/DataLink#11]
DataLink 1.0 made extensive use of the term "resource" to most often designate "endpoints". We will replace resource by "endpoint" when  appropriate

**Comment by lmichel** [comment]
Agree. The word "resource" is so much used in our business that we often  do not see  what does it mean exactly. We have better to replace it as often as possible.

**Comment by Bonnarel** [comment]
Done by merge of PR #19
