### ISSUE TITLE
URL with URI fragments

### ISSUE THREAD

**Issue by Bonnarel** [ivoa-std/DataLink#15]
some DataLink target files may have a complex structure (zip or tar archives, MEF, HDF 5, etc...)
We could manage this to allow fragments in the url to point on files into a retrievable archive. The syntax will be dependant of the mime-type of the complex file. There will be one row per subpart of the file. This is tacled in pull request #18. This use case could also be managed in the context of SODA (see SODA-next)

**Comment by robyww** [comment]
I am not quite sure what you mean by this. For example, if you can have a URL to a multi-HDU FITS file. I would expect the URL to be the same for each row (since it is the same file) and them some indication of which extension to use. 

Maybe a simple example would help.

**Comment by Bonnarel** [comment]
Yes Rob in case of MEF : "same URL" + "#" + "HDU number or name"


Le 18/10/2019 à 17:42, Trey Roby a écrit :

**Comment by robyww** [comment]
So to retrieve the FITS the client would be required to strip the `"#" + "HDU number or name"`? This could be done but seems really obscure.

**Comment by Bonnarel** [comment]
Hi Trey, this syntax is consistent with the so called "Fragment 
identifiers" of W3C

https://en.wikipedia.org/wiki/Fragment_identifier

or

https://tools.ietf.org/html/rfc3986#section-3.5

The base part is the dereferencable URL of the whole Fits file.

When the media type / mime type in the column content-type will indicate 
we have a MEF with HDU we know that we have to look a syntax for HDU 
reference in the fragment.

See section 3.5 of the RFC

But if you have a better idea to reference that the discussion is open

Cheers

François



Le 18/10/2019 à 19:02, Trey Roby a écrit :

**Comment by robyww** [comment]
If we were starting from scratch I would say that it makes more sense to add another column, but I think you said that you did not want to do that. 

We had some discussion at IPAC and "Fragment identifiers" seems to be reasonable but does create a little more work.

_A little background to my thinking:_
Just to give a little perspective from how we would handle this from the client side: Usually the data is related in a MEF.  So the client really needs to know two things. What in in the file and that the data is coming from a single file. This proposal makes it easier to know what is in the file but a little harder to know that they are all coming from one file. Ultimately the client will be required to go through each URLs of the DataLink table and strip off all the fragments and then compare the URLs to be able to group the data for the user.  

So the HDU's in a MEF are not necessary independent and the UI needs enough information to figure this out.

This proposal does allow for all of this, it just requires some processing.

**Comment by lmichel** [comment]
I think it is not a big job for the client to split the # 
This implicitly supposes that the stripped url returns the whole dataset . I do not see any counter example.

**Comment by robyww** [comment]
Well that is what is a little weird about using the `#`. The service  should return the whole FITS file in all cases. Maybe the `#` documenting  the HDU but it needs to return the whole FITS file.  You will almost always want the header from the HDU and the root  header. Now days some HDU will reference other HDUs. 

Ultimately the whole FITS should be returned and the fragment specifier should only be for documentation purposes.

**Comment by lmichel** [comment]
When I'm reading the thread, I'm wondering why we have to take care about the # fragment. Each dataLink row has its on URLs which can (or not) contain a fragment, whatever it is. The row description has to specify what is exactly returned by the server, but clients shouldn't have to do any interference based on the URL structure.

**Comment by Bonnarel** [comment]
Done with merge of PR #18
