### ISSUE TITLE
insisting on the importance of using the description field

### ISSUE THREAD

**Issue by Bonnarel** [ivoa-std/DataLink#16]
The description field may be a way for human readers to distinguish between links sharing the same semantic tag and content-type. the "should" is replaced by a more suggesting "SHOULD". Tackled in pull request #18

**Comment by mbtaylor** [comment]
I don't object to the change, but note that in the _Conformance-related definitions_ section at the head of the document, it expicitly says "(in upper or lower case)" about usage of terms like SHOULD, so the meaning of the text is not changed by this edit.

**Comment by Bonnarel** [comment]
Hi Mark

I agree that this change is only visual. But in that case it has better 
chance to be noticed by implementers.

The capital letter insistance is related to a closeby addition in the 
sentence :

it is intended for display by interactive applications*and very 
important to help user distinguish links with same semantics (see 
below)**.*

REgards
François



Le 23/11/2019 à 12:34, Mark Taylor a écrit :

**Comment by Bonnarel** [comment]
Done with merge of PR #18
