### ISSUE TITLE
Missing text in sec 4.4

### ISSUE THREAD

**Issue by mbtaylor** [ivoa-std/DataLink#2]
Section 4.4 of the published 1.0 REC contains the text:

> "Since the capability being described is RESTful and inputs are , the caller must recognise..."

I've interpolated "`{\em [?missing text?]}`" for now, but this should be fixed.

**Comment by Bonnarel** [comment]
I presume the missing words  "fixed" ---> "and inputs are fixed" because the values for the standard parameters of each VOSPACE end point is given in input PARAMS of the descriptor, but it's better to ask Pat wh write this one.
