### ISSUE TITLE
Missing ID in Self-Describing Service example?

### ISSUE THREAD

**Issue by mbtaylor** [ivoa-std/DataLink#3]
In the example in section 4.6, the inputParam with `name="ID"` has the attribute `ref="primaryID"`.  But none of the columns in the results table has a matching ID value.  So this example looks either broken or at least unhelpfully incomplete.

Should the FIELD with `name="ID"` also have `ID="primaryID"`?

**Comment by Bonnarel** [comment]
Yes this ref is obviously wrong and can be suppressed. Anyway the example for self description will change in 1.1

**Comment by Bonnarel** [comment]
Done with PR #4 which is now merged. requires an erratum in 1.0

**Comment by pdowler** [comment]
fixed in #4
