### ISSUE TITLE
An implementation appendix was missing.

### ISSUE THREAD

**Issue by Bonnarel** [ivoa-std/DataLink#31]
Some text guiding implementers on how to use DataLink, recognize its endpoints in various contexts was missing. It can be in Appendix (solution I prefer) or in an independant implementation note . See pull request #32

**Comment by lmichel** [comment]
I support the idea of an appendix, so that readers can get a straightforward access to an example sample

**Comment by pdowler** [comment]
This is now done via the implementation note (DataLinkImpl.tex)
