### ISSUE TITLE
VOResource representation for RofR inclusion

### ISSUE THREAD

**Issue by theresadower** [ivoa-std/DataLink#47]
Each IVOA standard is assigned an ivoid for the purposes of reference in other standards documents; DataLink's is ivo://www.ivoa.net/std/DataLink .

By design, the Registry of Registries should contain a VOResource representation of the standards document itself. Currently, the RofR does not include a DataLink resource. (not listed in: http://rofr.ivoa.net/oai?verb=ListRecords&metadataPrefix=ivo_vor&set=Standard). In the volute repository, this was listed in an XML file with extension .vor in the same directory as the TeX and other main documents for the standard. We should have a .vor file in the repository for each document in ivoa-std as we move to GitHub. (RegistryInterface as an example: ivoa-std/RegistryInterface#1)

The ivoa-std DataLink repo should have a .vor file representation at the top level, kept current with the version of DataLink and passed to the maintainers of the RofR.

*

I can volunteer to put together the file here in a branch and PR as we did for VOTable, and folks can add more details, if none of the current authors/editors want to take it on.

**Comment by msdemlei** [comment]
On Fri, May 15, 2020 at 01:08:12PM -0700, theresa dower wrote:
> I can volunteer to put together the file here in a branch and PR as
> we did for VOTable, and folks can add more details, if none of the
> current authors/editors want to take it on.

No need to -- I had actually made one on volute, but apparently it
never got sent to the RofR.

I've created PR #48 to put that into Datalink, and if whoever merges
this sends the record to the RofR right away, we're fine from that
perspective for 1.0.

**Comment by theresadower** [comment]
Excellent, thank you! I'd been searching RofR and GitHub for resources, but hadn't checked all the volute repositories for ones that didn't make it to RofR. I'll make sure to look there for the remainder.

**Comment by theresadower** [comment]
Emailed RofR, datalink will be added along with votable  when they get a chance.
