### ISSUE TITLE
Service descriptor is specifying a data product or a web page that should be opened.

### ISSUE THREAD

**Issue by robyww** [ivoa-std/DataLink#52]
Most service descriptors specify data products that can be downloaded and possibly visualized. However a powerful application of service descriptors is to specify web pages or web apps. In this case the consumer for the service descriptors needs a way to know that the url is not to be downloaded but should be opened in the web browser.

Currently we are looking at the `content_type` to see if it is `text/html`. If this is the best solution then it would be good if the standard could specifically call it out.

**Comment by robyww** [comment]
One more thing - this issue also exist in a simple data link url as well.

**Comment by Bonnarel** [comment]
Hum, not sure I catch your point actually. If the content_type is "text/html" (and I confirm that the new version will have and optional  "content-type" PARAM in the descriptor) what other choice can we have to send the link to the browser ? What you ask is to describe this use case explicitly in the content_type subsection ?

**Comment by robyww** [comment]
I think I am telling you what we had to do. My issue is there is not a way besides some sort of content-type guess to tell the difference between a data product and a web page that should be opened. If content-type is the right way to do it then it makes sense to call it out. However, I could not tell what the right way to do it is. This seems to me to be a important way to use service descriptors that might have been overlooked in the past.

**Comment by pdowler** [comment]
clarified in doc
