### ISSUE TITLE
In General introduction  the scope of "DataLinking" is restricted to datasets

### ISSUE THREAD

**Issue by Bonnarel** [ivoa-std/DataLink#6]
In General introduction we should extend the scope of "DataLinking"
outside the original niche of resources attached to datasets. the proposed change is to replace "datasets" by "items". Since version 1.0 became a recommendation, DataLink was used not only in the context of datasets discovery but also more widely to a attach resources to sources in a catalogue or to lines in a main table.

**Comment by lmichel** [comment]
Items is very vague.
Can we just  introduce here a new term such as "linked resources" with an appropriate acronym "LR"?
