### ISSUE TITLE
DataLink version identifier

### ISSUE THREAD

**Issue by mbtaylor** [ivoa-std/DataLink#62]
Section 2.2 says:
> Operators still wishing to declare {links} endpoints can do this by giving a capability with a standardID of `ivo://ivoa.net/std/DataLink#links-1.0`

Versions in the VO always make my head hurt, but I *think* it's OK for this to still contain a "1.0" even though this is DataLink 1.1, i.e. this text is correct.  Can somebody (@msdemlei?) confirm that's the case?  If so, then it might be a good idea to add a comment to the text reassuring readers as clueless as me that this is not a typo.

Related: sec 3.3.1 recommends identifying output VOTables like
```
  <INFO name="standardID" value="ivo://ivoa.net/std/DataLink#links-1.?"/>
```
is that correct?  I'd expect the version number in that IVOID to be the same as the one defined in section 2.2.

**Comment by pdowler** [comment]
Given the way we're adding new optional features, the standardID can remain unchanged and the example should say #links-1.0.
