### ISSUE TITLE
night build of the DataLink document

### ISSUE THREAD

**Issue by robyww** [ivoa-std/DataLink#66]
Is there a way to see a PDF of a nightly build of the document? I really would prefer not to go the trouble of figuring out all the LaTEX.

**Comment by robyww** [comment]
I just the `Auto PDF Preview` release. That's great!

**Comment by Bonnarel** [comment]
bug in preview.yml action solved with help of Gregory and James.
Thanks to them !
Le 04/11/2021 à 14:38, Trey Roby a écrit :
