### ISSUE TITLE
Add new use cases in 1.2

### ISSUE THREAD

**Issue by Bonnarel** [ivoa-std/DataLink#7]
As a matter of consequence of issue #6 we should add use cases in section 1.2 such as
- attaching datasets (Images, spectra, time series ... ) to sources in a catalog.
- provenance metadata related to dataset (or other items) entities

**Comment by lmichel** [comment]
I very strongly support the bullet #1 
I strongly support the bullet #2

**Comment by robyww** [comment]
Yes, at IPAC we are about to do this. I think it should be in the standard.
