### ISSUE TITLE
Architecture diagram absent in auto-built PDF

### ISSUE THREAD

**Issue by mbtaylor** [ivoa-std/DataLink#79]
The pre-release auto-pdf-preview currently available at https://github.com/ivoa-std/DataLink/releases/tag/auto-pdf-preview contains the PDF fallback text _("PDF fallback: A conversion from SVG to PDF failed. This is probably because inkscape is not installed. While SVG is not supported by the major TeX engines, it is recommended to commit built PDFs to the VCS.")_ where the architecture diagram should be.

I get something similar when I build it locally, but I never know whether that's my misconfiguration.

Should the arch diagram PDF be added to the commits?  At any rate something should be done to fix the auto-preview.

**Comment by pdowler** [comment]
I'm not a fan of committing anything that is built from source; will try to fix the build and might have to cave and commit the pdf.

**Comment by mbtaylor** [comment]
Still broken as of now.  Also, if the PDF is committed it reduces the burden (of installing extra software) on other people building the document for themselves.
