### ISSUE TITLE
Under-documentation of inputParam usage

### ISSUE THREAD

**Issue by mbtaylor** [ivoa-std/DataLink#80]
After wading through it a dozen times or so, I still find the description of service descriptors in the DataLink document (section 4) tough going.

One specific issue that I think could improve matters would be better description of what goes in the inputParams GROUP (described in the last paragraph of sec 4.1).  It doesn't say anything about what goes in PARAM `value` attributes; as far as I can tell, for PARAMs without a ref attribute, if the value attribute is non-empty (though not non-null, because PARAM constraints forbid that) it means a value for that service parameter which is fixed, and if it's empty it means that the user must be requested to supply a value.  Could some more explicit text be written here to clarify things?

For background, here is a comment I've written in my service descriptor implementation code:
```
 * <p>This class divides the input
 * {@link uk.ac.starlink.votable.datalink.ServiceParam}s defined by the
 * <code>ServiceDescriptor</code> into three different categories
 * according to how their values are acquired at service invocation time:
 * <ul>
 * <li><em>row</em> parameters:
 *     the value is acquired from a cell of the result table;
 *     a table row object must be supplied to obtain the value
 *     </li>
 * <li><em>fixed</em> parameters:
 *     the value is provided by the parameter definition
 *     and fixed for all invocations
 *     </li>
 * <li><em>user</em> parameters:
 *     the value must be supplied for each invocation by the user
 *     </li>
 * </ul>
 *
 * <p>The DataLink-1.0 standard is not very explicit about this distinction,
 * but the above division appears(?) to be the consensus of the standard
 * authors.  This does not however prevent service invocations filling
 * these parameter values differently than according to the above outline.
 * For instance, users may be given the option to change the values of
 * fixed or row parameters for a given invocation.
```
That may or may not be doing the right thing/making the right assumptions... but it would be nice to have to do less guesswork.

**Comment by Bonnarel** [comment]
I agree with these distinctions. I try to write a PR to make that more explicit.

**Comment by pdowler** [comment]
resolved
