### ISSUE TITLE
UCD for ID column in {links} service output?

### ISSUE THREAD

**Issue by gpdf** [ivoa-std/DataLink#89]
My colleague @rra has pointed out that the `ID` output column of a {links} resource is frequently used, by design, as the input to the `ID` parameter of a SODA service, and that there is a difference between the UCDs we prescribe for the two.

Erratum 1 to SODA 1.0 (accepted: 2019-05-12) states that the `ID` input parameter should have the UCD "meta.id;meta.dataset" (replacing the anomalous "meta.ref.url;meta.curation.SODA" from the original SODA 1.0).

The output column `ID` from a {links} resource is specified in DataLink 1.0 and the current DataLink 1.1 WD to have the UCD "meta.id;meta.main".

Arguably, only the P/primary parts of the UCD might need to match (certainly I think that there are few/no good reasons to use "meta.main" to describe an *input* parameter to a service), but Russ and I are wondering about the above mismatch, and I'd like to ask that we at least consider whether "meta.id;meta.dataset;meta.main" might make sense for the `ID` output of a {links} resource.

If we'd rather not make this change - e.g., for backward compatibility reasons, or because we think that `ID` in a {links} response may not always refer to a "dataset" (that's perhaps plausible) - perhaps this could at least trigger a discussion of whether we have **any** expectations regarding compatibility of UCDs between outputs and their subsequent re-use as inputs.  We could also just establish some expectations for whether we want to try to make things match up better in the future in other standards.

----

A further point: it is arguable that from a *client software* perspective, if a VOTable response I get from a service has a service descriptor telling me to plug column `X` of the table into input `Y` of some service, I am obligated to take that at face value and not attempt to validate the compatibility of the UCDs for `X` and `Y`.  It might only be for a community VO validator to raise that question, or for a data *publisher* to take care that the service descriptors it publishes obey some compatibility principles.

----

Note also that, according to DataLink 1.0/1.1, an input to `ID` for a {links} resource is often likely to be an ObsCore `obs_publisher_did` (though it's not required to be) and that that attribute (according to ObsCore 1.1 erratum 1) has the UCD "meta.ref.ivoid".

Arguably "meta.ref.ivoid" is semantically a subclass, as it were, of "meta.id" (though I don't think we say that formally anywhere), so I would have no hesitation saying that it's obviously valid to use a "meta.ref.ivoid" as a "meta.id".  But, since IVOIDs can refer to things other than datasets, maybe a better UCD for `obs_publisher_did` (and `obs_creator_did`) in ObsCore might be "meta.ref.ivoid;meta.dataset", since a "dataset identifier" is obviously referring to a dataset?

**Comment by msdemlei** [comment]
On Tue, Aug 02, 2022 at 07:39:02PM -0700, gpdf wrote:
> A further point: it is arguable that from a *client software*
> perspective, if a VOTable response I get from a service has a
> service descriptor telling me to plug column `X` of the table into
> input `Y` of some service, I am obligated to take that at face
> value and not attempt to validate the compatibility of the UCDs for
> `X` and `Y`.  It might only be for a community VO validator to
> raise that question, or for a data *publisher* to take care that
> the service descriptors it publishes obey some compatibility
> principles.

I'd argue against making any requirements on UCDs here.  UCDs are
mainly intended for ad-hoc or discovery use, like:  

* a client sees an arbitrary VOTable and wants to get an idea what
  kind of physics is represented in order to suggest plots for it,
  perhaps match it with columns in other tables or similar.

* a client is looking for tables having a particular sort of data in
  the registry.

Except for SIAP 1, protocols do not use UCDs but either bespoke
column names (preferred from my perspective) or utypes, and that
makes good sense.  I think we should, indeed, think about what to
conclude from that fact for future standardisation (also with a view
to the plethora of errata dealing with UCDs).  But that belongs to
the DAL and Semantics mailing lists rather than a github issue.

**Comment by Bonnarel** [comment]
Hi Gregory, all;
Le 03/08/2022 à 04:39, gpdf a écrit :
>
> My colleague @rra <https://github.com/rra> has pointed out that the 
> |ID| output column of a {links} resource is frequently used, by 
> design, as the input to the |ID| parameter of a SODA service, and that 
> there is a difference between the UCDs we prescribe for the two.
>
> Erratum 1 to SODA 1.0 (accepted: 2019-05-12) states that the |ID| 
> input parameter should have the UCD "meta.id;meta.dataset" (replacing 
> the anomalous "meta.ref.url;meta.curation.SODA" from the original SODA 
> 1.0).
>
> The output column |ID| from a {links} resource is specified in 
> DataLink 1.0 and the current DataLink 1.1 WD to have the UCD 
> "meta.id;meta.main".
>
> Arguably, only the P/primary parts of the UCD might need to match 
> (certainly I think that there are few/no good reasons to use 
> "meta.main" to describe an /input/ parameter to a service), but Russ 
> and I are wondering about the above mismatch, and I'd like to ask that 
> we at least consider whether "meta.id;meta.dataset;meta.main" might 
> make sense for the |ID| output of a {links} resource.
>
> If we'd rather not make this change - e.g., for backward compatibility 
> reasons, or because we think that |ID| in a {links} response may not 
> always refer to a "dataset" (that's perhaps plausible) -
>
Obviously the changes in DataLink 1.1 explicitly extend the scope of the 
{links} endpoint beyond the #this=dataset use case (eg. taking into 
account also the use case #this=source in a catalog). SODA or most of 
the custom services are more specific. SODA restricted to datasets. This 
advocates for letting the two ucds independant I guess.
>
> perhaps this could at least trigger a discussion of whether we have 
> *any* expectations regarding compatibility of UCDs between outputs and 
> their subsequent re-use as inputs. We could also just establish some 
> expectations for whether we want to try to make things match up better 
> in the future in other standards.
>
> ------------------------------------------------------------------------
>
> A further point: it is arguable that from a /client software/ 
> perspective, if a VOTable response I get from a service has a service 
> descriptor telling me to plug column |X| of the table into input |Y| 
> of some service, I am obligated to take that at face value and not 
> attempt to validate the compatibility of the UCDs for |X| and |Y|. It 
> might only be for a community VO validator to raise that question, or 
> for a data /publisher/ to take care that the service descriptors it 
> publishes obey some compatibility principles.
>
The tricky point here  is that service descriptors may be retrieved in 
various contexts : DataLink {links} response, any VO service VOTable 
response or service autodescription. This makes almost impossible to 
have identical ucds in all these contexts apart from letting the service 
define its own for the input parameters. Obviously the main term should 
be identical or parent if we are consistent. But the secondary may differ.
> ------------------------------------------------------------------------
>
> Note also that, according to DataLink 1.0/1.1, an input to |ID| for a 
> {links} resource is often likely to be an ObsCore |obs_publisher_did| 
> (though it's not required to be) and that that attribute (according to 
> ObsCore 1.1 erratum 1) has the UCD "meta.ref.ivoid".
>
And we can have the service descriptor directly in the ObsCore document 
(without using any {links} response.

**Comment by Bonnarel** [comment]
Le 03/08/2022 à 09:03, msdemlei a écrit :
> On Tue, Aug 02, 2022 at 07:39:02PM -0700, gpdf wrote:
> > A further point: it is arguable that from a *client software*
> > perspective, if a VOTable response I get from a service has a
> > service descriptor telling me to plug column `X` of the table into
> > input `Y` of some service, I am obligated to take that at face
> > value and not attempt to validate the compatibility of the UCDs for
> > `X` and `Y`. It might only be for a community VO validator to
> > raise that question, or for a data *publisher* to take care that
> > the service descriptors it publishes obey some compatibility
> > principles.
>
> I'd argue against making any requirements on UCDs here. UCDs are
> mainly intended for ad-hoc or discovery use, like:
>
> * a client sees an arbitrary VOTable and wants to get an idea what
> kind of physics is represented in order to suggest plots for it,
> perhaps match it with columns in other tables or similar.
>
> * a client is looking for tables having a particular sort of data in
> the registry.
Fully agree with Markus here.
>
> Except for SIAP 1, protocols do not use UCDs but either bespoke
> column names (preferred from my perspective) or utypes, and that
> makes good sense. I think we should, indeed, think about what to
> conclude from that fact for future standardisation (also with a view
> to the plethora of errata dealing with UCDs). But that belongs to
> the DAL and Semantics mailing lists rather than a github issue.

SIAP1 feedback was the main reason to introduce utypes in the following 
version of VOTable at the time (~2005 ?).

Obviously using the same attribute for an (accurate) role and a (fuzzy) 
physical characterization was impossible.

**Comment by pdowler** [comment]
I think I disagree with the basic statement that this is by design. The ID column in the {links} output simply echoes the input ID value(s) so the client can make sense of the output in the case where there are multiple input ID(s). 

if there is a SODA service descriptor, the ID for the SODA service call could be:

1. ref to the ID column in the {links} table
2. ref to a different column in the {links} table
3. a value attribute in the descriptor of the ID param
4. hard-coded into the SODA accessURL (least desireable given SODA-1.0)

Option 2 would be common when a single publisher ID maps to mutliple "files" that the SODA service can operate on and the links service wants to output a generic descriptor that applies to multiple links.

Option 3 would be common if multiple files (as above) and the links service was generating a custom descriptor for each file that could be cut.

CADC currently does 3 but I have a plan to do 2 in some cases and 3 in others (for reasons); both comply to the spec. We also have a use case for something like 4 to be discussed.

So, I dont' know which UCDs are best, but they don't need to agree.

**Comment by gpdf** [comment]
I'm convinced by the above.  It's fine with me to close this issue.
