### ISSUE TITLE
Outdated UCD for ObsCore obs_publisher_did

### ISSUE THREAD

**Issue by gpdf** [ivoa-std/DataLink#90]
In the current (2021-11-15) DataLink WD, in section 4.4 "Example: Service Descriptor for the {links} Capability", there is a reference to `obs_publisher_did` from "ObsCore 1.0", and a mention of its UCD as "meta.ref.url;meta.curation".  This should be changed in DataLink 1.1 to refer to ObsCore 1.1, which is approved, and to its Erratum 1, which revises the UCD for `obs_publisher_did` from "meta.ref.uri;meta.curation" to "meta.ref.ivoid".

**Comment by pdowler** [comment]
updating this example with several other editorial tweaks
